### ISSUE TITLE
AppImage support

### ISSUE THREAD

**Issue by MakuSensei** [rescatux/rescapp#1]
Hello, I wanted to recommend that this packaged in AppImage format would be good for its free use in any kind of distro

**Comment by adrian15** [comment]
I'm not sure I want to maintain the source code of all the auxiliar programs that Rescapp uses so that I can properly package it in AppImage.

Anyways I have just overlooked AppImage and I will look into it in more detail later.

Any suggestion on how to modify rescapp itself so that it's easier to package into AppImage by someone else is welcome.
