### ISSUE TITLE
make uninstall

### ISSUE THREAD

**Issue by MakuSensei** [rescatux/rescapp#2]
hello, I installed it in fedora and it does not work.
I want to de-stamp it and I can not

**Comment by adrian15** [comment]
> I want to de-stamp it and I can not

As I expected this program to be packaged into a distribution packages (which usually take care of uninstalling the package) I had not thought about implementing make uninstall.

I will try to implement a safe make uninstall because I install many files in a recursive manner. I'm kind of a GNU make newbie and I don't want to delete more information than the one it has been installed.

**Comment by adrian15** [comment]
> hello, I installed it in fedora and it does not work.

Can you open a new issue on Rescapp not working on Fedora?

I want to debug this problem starting with you having installed all the dependencies describe on the INSTALL file in a separate bug. You can also join me at #rescatux channel at freenode irc if you happen to be online right now.

Thank you.
