### ISSUE TITLE
Broken Grub2 password: Can I fix this issue with your tools?

### ISSUE THREAD

**Issue by D-signr** [rescatux/rescapp#64]
Hello,

Is Rescatux or Super Grub2 Disk able to fix my system when the problem is as follows:

I set up an encrypted password to Grub2 but weren’t aware about keyboard character limitations in Grub2. I corrected wrong characters on my keyboard to match US English keyboard but there’s still one character that isn’t possible to be typed.
Then I tried with my Ubuntu Server 18.04 disc in live mode and with that I was able to do everything else but not to save changes (and I think my chrooting was correctly done, so that shouldn't be the reason why saving wasn't possible).
Can I get rid of the problem with your software, as currently I can't get in to my server?
(I haven't encrypted the disc containing the system and so it should be repairable but how?)
with best regs
Ilmo

**Comment by adrian15** [comment]
Option 1)

You can use Super Grub2 Disk to boot into the kernel+initrd directly. This option does not read your grub.cfg and thus it bypasses the grub.cfg password.

The option is "Boot Operating Systems" where you choose a Linux entry.

Unfortunately if you boot in UEFI mode the current SG2D releases (even beta ones) do not show those entries. I thought 

Option 2)

Tell me which howto you used to add a password to grub2. I might be able to develop a new option for Rescapp so that I comment or strip the password settings from grub.cfg.

By the way, are you able to get an Internet connection from inside Rescatux? I ask this question to know if I can ask you to update Rescapp from inside Rescatux or if I will have to upload an entire Rescatux.

Thank you.

**Comment by D-signr** [comment]
This server is UEFI 2.4 Compliant. There wasn't "Boot Operating Systems" -option available with exactly that term. I had some trial and error until I managed to boot into the system. What I did: I enabled LVM and let the SG2D detect available options from my disc. From that list I chose Ubuntu and from there on, everything went like in a normal boot-up. Now the problem is solved.

This is truly a great set of tools for boot emergency cases. Thanks a lot!
