### ISSUE TITLE
How to fix mismatched GPT and MBR partition

### ISSUE THREAD

**Issue by candrapersada** [rescatux/rescapp#75]
How to fix mismatched GPT and MBR partition?
```
MBR: MBR only
BSD: not present
APM: not present
GPT: Damaged
```

**Comment by adrian15** [comment]
Not sure there is a tool in Rescapp for this specific task.

If you find any a manual workaround please document it here so that we can add it as an option to Rescapp.

**Comment by jtruitt** [comment]
not sure on this but, I did see that a Partition could be changed using the diskmngr tool in windows, but it will wreck the install so if you have something you want on there you may want to find a gentler tool. 

I am hoping that i can do the same thing that you are thinking on a Windows 10 was installed on MBR and I was able to run the MBR2GPT tool on it, but when I rebooted the drive looks confused because i have to repair it and i am not sure if i need MBR or if i can force it to GPT
